### ISSUE TITLE
Error when delete key and then save fine in demo.c 

### ISSUE THREAD

**Issue by ssht428** [univrsal/mini.c#1]
Hardware : Thinkbook T16 Gen3
Software : Win10 + VS2022 + Qt5

Errror: Exception thrown at 0x00007FFEC345AC87 (ucrtbased.dll) in demo.exe: 0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFF.
![error_when_mini_save_printf](https://github.com/univrsal/mini.c/assets/25168383/17c3b416-a505-43ac-83b3-19690f31996d)

After debug step by step, i locate the error occur in 

the call step is : [demo.c line80 : mini_delete_value(ini, "test_group", "id");] -> [mini.c line455 :    int wrote_something = write_group(grp, f); ] -> [ mini.c line290 :  while (cval){....}]
because cval point to unknown address,so it rise error.

**Comment by ssht428** [comment]
another weird thing is : #define _WIN32,
no mater what you config your project, the predefine WIN32 is always enabled.
it will choose those code under WIN32.....

**Comment by univrsal** [comment]
> another weird thing is : #define _WIN32,
> no mater what you config your project, the predefine WIN32 is always enabled.
> it will choose those code under WIN32.....

That's normal since you're compiling under windows.
